INSERT INTO certificates VALUES (1, 'C1', 'Desk1', 10, 10, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP);
INSERT INTO certificates VALUES (2, 'C2', 'Desk2', 20, 20, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP);
INSERT INTO certificates VALUES (3, 'C3', 'Desk3', 30, 30, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP);
INSERT INTO certificates VALUES (4, 'C4', 'Desk4', 40, 40, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP);
INSERT INTO certificates VALUES (5, 'C5', 'Desk5', 50, 50, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP);